remote_theme: pages-themes/slate
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
title: GreenBlue Security
description: Personal Cybersecurity Research & Insights
author: "Abraham Judisch"
email: greenbluesec@proton.me

# Social links (optional)
social:
  github: https://github.com/GreenBlueSec
  linkedin: https://www.linkedin.com/in/abrahamjudisch-507sec/

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5

sass:
  style: compressed

# Add this under existing fields
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# Enable custom CSS
include:
  - assets/css/style.css