# We are no longer using a remote theme
theme: null

# Ensure custom CSS is included
include:
  - assets/css/style.css

# Plugins (still useful)
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: GreenBlue Security
description: Personal Cybersecurity Research & Insights
author: "Abraham Judisch"
email: greenbluesec@proton.me

# Social links (optional)
social:
  github: https://github.com/GreenBlueSec
  linkedin: https://www.linkedin.com/in/abrahamjudisch-507sec/

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post